/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFerramentasAiRouteImport } from './routes/api/ferramentas-ai'
import { Route as ApiCreatePixRouteImport } from './routes/api/create-pix'
import { Route as ApiPublicWebhooksSharkhubRouteImport } from './routes/api/public/webhooks/sharkhub'
import { Route as ApiPublicWebhooksIronpayRouteImport } from './routes/api/public/webhooks/ironpay'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFerramentasAiRoute = ApiFerramentasAiRouteImport.update({
  id: '/api/ferramentas-ai',
  path: '/api/ferramentas-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatePixRoute = ApiCreatePixRouteImport.update({
  id: '/api/create-pix',
  path: '/api/create-pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksSharkhubRoute =
  ApiPublicWebhooksSharkhubRouteImport.update({
    id: '/api/public/webhooks/sharkhub',
    path: '/api/public/webhooks/sharkhub',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksIronpayRoute =
  ApiPublicWebhooksIronpayRouteImport.update({
    id: '/api/public/webhooks/ironpay',
    path: '/api/public/webhooks/ironpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/ferramentas-ai': typeof ApiFerramentasAiRoute
  '/api/public/webhooks/ironpay': typeof ApiPublicWebhooksIronpayRoute
  '/api/public/webhooks/sharkhub': typeof ApiPublicWebhooksSharkhubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/ferramentas-ai': typeof ApiFerramentasAiRoute
  '/api/public/webhooks/ironpay': typeof ApiPublicWebhooksIronpayRoute
  '/api/public/webhooks/sharkhub': typeof ApiPublicWebhooksSharkhubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/ferramentas-ai': typeof ApiFerramentasAiRoute
  '/api/public/webhooks/ironpay': typeof ApiPublicWebhooksIronpayRoute
  '/api/public/webhooks/sharkhub': typeof ApiPublicWebhooksSharkhubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/create-pix'
    | '/api/ferramentas-ai'
    | '/api/public/webhooks/ironpay'
    | '/api/public/webhooks/sharkhub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/create-pix'
    | '/api/ferramentas-ai'
    | '/api/public/webhooks/ironpay'
    | '/api/public/webhooks/sharkhub'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/create-pix'
    | '/api/ferramentas-ai'
    | '/api/public/webhooks/ironpay'
    | '/api/public/webhooks/sharkhub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiCreatePixRoute: typeof ApiCreatePixRoute
  ApiFerramentasAiRoute: typeof ApiFerramentasAiRoute
  ApiPublicWebhooksIronpayRoute: typeof ApiPublicWebhooksIronpayRoute
  ApiPublicWebhooksSharkhubRoute: typeof ApiPublicWebhooksSharkhubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ferramentas-ai': {
      id: '/api/ferramentas-ai'
      path: '/api/ferramentas-ai'
      fullPath: '/api/ferramentas-ai'
      preLoaderRoute: typeof ApiFerramentasAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-pix': {
      id: '/api/create-pix'
      path: '/api/create-pix'
      fullPath: '/api/create-pix'
      preLoaderRoute: typeof ApiCreatePixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/sharkhub': {
      id: '/api/public/webhooks/sharkhub'
      path: '/api/public/webhooks/sharkhub'
      fullPath: '/api/public/webhooks/sharkhub'
      preLoaderRoute: typeof ApiPublicWebhooksSharkhubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/ironpay': {
      id: '/api/public/webhooks/ironpay'
      path: '/api/public/webhooks/ironpay'
      fullPath: '/api/public/webhooks/ironpay'
      preLoaderRoute: typeof ApiPublicWebhooksIronpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiCreatePixRoute: ApiCreatePixRoute,
  ApiFerramentasAiRoute: ApiFerramentasAiRoute,
  ApiPublicWebhooksIronpayRoute: ApiPublicWebhooksIronpayRoute,
  ApiPublicWebhooksSharkhubRoute: ApiPublicWebhooksSharkhubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
