/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFerramentasAiRouteImport } from './routes/api/ferramentas-ai'
import { Route as ApiCreatePixRouteImport } from './routes/api/create-pix'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as ApiPublicWebhooksIronpayRouteImport } from './routes/api/public/webhooks/ironpay'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFerramentasAiRoute = ApiFerramentasAiRouteImport.update({
  id: '/api/ferramentas-ai',
  path: '/api/ferramentas-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatePixRoute = ApiCreatePixRouteImport.update({
  id: '/api/create-pix',
  path: '/api/create-pix',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicWebhooksIronpayRoute =
  ApiPublicWebhooksIronpayRouteImport.update({
    id: '/api/public/webhooks/ironpay',
    path: '/api/public/webhooks/ironpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/ferramentas-ai': typeof ApiFerramentasAiRoute
  '/api/public/webhooks/ironpay': typeof ApiPublicWebhooksIronpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/ferramentas-ai': typeof ApiFerramentasAiRoute
  '/api/public/webhooks/ironpay': typeof ApiPublicWebhooksIronpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/create-pix': typeof ApiCreatePixRoute
  '/api/ferramentas-ai': typeof ApiFerramentasAiRoute
  '/api/public/webhooks/ironpay': typeof ApiPublicWebhooksIronpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/create-pix'
    | '/api/ferramentas-ai'
    | '/api/public/webhooks/ironpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/create-pix'
    | '/api/ferramentas-ai'
    | '/api/public/webhooks/ironpay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/api/create-pix'
    | '/api/ferramentas-ai'
    | '/api/public/webhooks/ironpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiCreatePixRoute: typeof ApiCreatePixRoute
  ApiFerramentasAiRoute: typeof ApiFerramentasAiRoute
  ApiPublicWebhooksIronpayRoute: typeof ApiPublicWebhooksIronpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ferramentas-ai': {
      id: '/api/ferramentas-ai'
      path: '/api/ferramentas-ai'
      fullPath: '/api/ferramentas-ai'
      preLoaderRoute: typeof ApiFerramentasAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-pix': {
      id: '/api/create-pix'
      path: '/api/create-pix'
      fullPath: '/api/create-pix'
      preLoaderRoute: typeof ApiCreatePixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhooks/ironpay': {
      id: '/api/public/webhooks/ironpay'
      path: '/api/public/webhooks/ironpay'
      fullPath: '/api/public/webhooks/ironpay'
      preLoaderRoute: typeof ApiPublicWebhooksIronpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiCreatePixRoute: ApiCreatePixRoute,
  ApiFerramentasAiRoute: ApiFerramentasAiRoute,
  ApiPublicWebhooksIronpayRoute: ApiPublicWebhooksIronpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
